//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by D:\git\TortoiseSI\src\Resources\TortoiseShellENG.rc
//
#define IDI_PULL                        5
#define IDD_PROPPAGE                    107
#define IDI_APP                         108
#define IDI_CHECKOUT                    121
#define IDI_UPDATE                      122
#define IDI_COMMIT                      123
#define IDI_ADD                         124
#define IDI_REVERT                      125
#define IDI_CLEANUP                     126
#define IDI_RESOLVE                     127
#define IDI_SWITCH                      128
#define IDI_MERGE                       129
#define IDI_IMPORT                      130
#define IDI_EXPORT                      131
#define IDI_COPY                        132
#define IDI_DELETE                      133
#define IDI_RENAME                      134
#define IDI_DIFF                        135
#define IDI_LOG                         136
#define IDI_ABOUT                       137
#define IDI_SETTINGS                    138
#define IDI_CREATEREPOS                 139
#define IDI_CONFLICT                    140
#define IDI_RELOCATE                    141
#define IDI_HELP                        142
#define IDI_SHOWCHANGED                 143
#define IDI_IGNORE                      144
#define IDS_VIEW_SANDBOX                172
#define IDS_CREATE_SANDBOX              173
#define IDS_MENU                        174
#define IDS_SANDBOX_NOTALLOWED1         175
#define IDS_IGNORE_SUBMENU              176
#define IDS_IGNORE_SUBMENU_DESC         177
#define IDS_LOCAL_CHANGES_DIFF          178
#define IDS_LOCAL_CHANGES_DIFF_DESC     179
#define IDS_VIEW_ANNOTATED_REVISION     180
#define IDS_VIEW_ANNOTATED_REVISION_DESC 181
#define IDS_VIEW_MEMBER_INFO            182
#define IDS_VIEW_MEMBER_INFO_DESC       183
#define IDS_VIEW_HISTORY                184
#define IDS_VIEW_HISTORY_DESC           185
#define IDS_ADD_NONMEMBER               186
#define IDS_ADD_NONMEMBER_DESC          187
#define IDS_CHECKOUT                    188
#define IDS_CHECKOUT_DESC               189
#define IDS_CHECKIN                     190
#define IDS_CHECKIN_DESC                191
#define IDS_DROP                        192
#define IDS_DROP_DESC                   193
#define IDS_LOCK                        194
#define IDS_LOCK_DESC                   195
#define IDS_REVERT                      196
#define IDS_REVERT_DESC                 197
#define IDS_RENAME                      198
#define IDS_RENAME_DESC                 199
#define IDS_MOVE                        200
#define IDS_MOVE_DESC                   201
#define IDS_VIEW_WORKINGFILECHANGES     202
#define IDS_VIEW_WORKINGFILECHANGES_DESC 203
#define IDS_SUBMIT_CP                   204
#define IDS_SUBMIT_CP_DESC              205
#define IDS_CLIENT_COMM_ERROR           206
#define IDS_CLIENT_COMM_TITLE           207
#define IDS_VIEW_MYREVIEWS              208
#define IDS_VIEW_MYREVIEWS_DESC         209
#define IDS_MERGE_CONFLICTS             210
#define IDS_MERGE_CONFLICTS_DESC        211
#define IDS_REMOVE_SUBMENU              212
#define IDS_REMOVE_SUBMENU_DESC         213
#define IDI_MENUSYNC                    321
#define IDI_REVISIONGRAPH               366
#define IDS_LOADING                     369
#define IDS_RESYNC                      370
#define IDS_RESYNC_ENTIRE_SANDBOX       371
#define IDS_DROP_SANDBOX                372
#define IDS_RETARGET_SANDBOX            373
#define IDS_MULTIPLE_SANDBOXES          374
#define IDS_VIEW_SANDBOX_DESC           375
#define IDS_RESYNC_DESC                 376
#define IDS_RESYNC_ENTIRE_SANDBOX_DESC  377
#define IDS_DROP_SANDBOX_DESC           378
#define IDS_RETARGET_SANDBOX_DESC       379
#define IDS_CREATE_SANDBOX_DESC         380
#define IDS_PROP_NAME_COLUMN            381
#define IDS_PROP_VALUE_COLUMN           382
#define IDS_PROP_MEMBER_REV             383
#define IDS_PROP_WORKING_REV            384
#define IDS_PROP_SANDBOX_NAME           385
#define IDS_PROP_STATUS                 386
#define IDS_PROP_LOCK_NAME              387
#define IDS_PROP_LOCK_CPID              388
#define IDS_PROP_LOCK_TYPE              389
#define IDS_PROP_WORKING_CPID           390
#define IDS_PROP_FILE_GROUP_NAME        391
#define IDS_PROP_LOCK_GROUP_NAME        392
#define IDS_PROP_FOLDER_GROUP_NAME      393
#define IDS_PROP_DEVPATH                394
#define IDS_PROP_PROJECT_NAME           395
#define IDS_PROP_SERVER_NAME            396
#define IDS_PROP_REVISION               397
#define IDS_VIEW_CHANGEPACKAGES         999
#define IDS_VIEW_CHANGEPACKAGES_DESC    1000
#define IDC_HEAD_HASH                   1001
#define IDC_LAST_HASH                   1002
#define IDC_SHELL_CURRENT_BRANCH        1003
#define IDC_HEAD_SUBJECT                1004
#define IDC_LAST_SUBJECT                1005
#define IDC_HEAD_AUTHOR                 1007
#define IDC_LAST_AUTHOR                 1008
#define IDC_HEAD_DATE                   1009
#define IDC_LAST_DATE                   1010
#define IDC_SHOWLOG                     1016
#define IDC_SHOWSETTINGS                1017
#define IDI_REPOBROWSE                  5145
#define IDI_BLAME                       5146
#define IDI_PATCH                       5147
#define IDI_CREATEPATCH                 5150
#define IDI_MENUFILE                    5154
#define IDI_MENUFOLDER                  5155
#define IDI_MENULINK                    5156
#define IDI_MENUMULTIPLE                5157
#define IDI_PROPERTIES                  5158
#define IDI_APPSMALL                    5160
#define IDI_CLIPPASTE                   5164
#define IDI_PUSH                        5166
#define IDI_CLONE                       5167
#define IDI_TAG                         5168
#define IDI_REBASE                      5169
#define IDI_COMBINE                     5170
#define IDI_SKIP                        5171
#define IDI_EDIT                        5172
#define IDI_SQUASH                      5173
#define IDI_PICK                        5174
#define IDI_MENUSENDMAIL                5175
#define IDI_COPYCLIP                    5176
#define IDI_THUMB_DOWN                  5178
#define IDI_THUMB_UP                    5179
#define IDI_DAEMON                      5180
#define IDI_MERGEABORT                  5181
#define IDI_LOCK                        5183
#define IDC_CONFIG_AUTOCRLF             11020
#define IDC_SHELL_REMOTE_BRANCH         11022
#define IDC_ESCAPEDURLLABEL             11023
#define IDC_CONFIG_SAFECRLF             11024
#define IDC_CONFIG_USERNAME             11025
#define IDC_CONFIG_USEREMAIL            11026
#define IDC_ASSUMEVALID                 11027
#define IDC_EXECUTABLE                  11028
#define IDC_SKIPWORKTREE                11029
#define IDC_STATIC_LASTMODIFIED         11030
#define IDC_SYMLINK                     11031
#define IDS_ETC                         11032
#define IDS_SHOWING_PARTIAL_RESULTS     11033
#define IDC_LIST2                       11033

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        5186
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         11034
#define _APS_NEXT_SYMED_VALUE           5122
#endif
#endif
