//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by D:\Project\TortoiseSI\src\Resources\TortoiseProcENG.rc
//
#define IDR_MAINFRAME                   1
#define IDD_SETTINGSPROXY               102
#define IDD_SETTINGSHOOKS               103
#define IDD_SETTINGSOVERLAY             106
#define IDD_SETTINGSSAVEDDATA           108
#define IDD_ABOUT                       129
#define IDD_LOGMESSAGE                  130
#define IDD_PROMPT                      131
#define IDD_SVNPROGRESS                 134
#define IDD_COMMITDLG                   135
#define IDD_SETTINGSMAIN                143
#define IDR_ANIMATION                   148
#define IDR_MOVEANI                     149
#define IDD_RENAME                      151
#define IDD_REPOSITORY_BROWSER          153
#define IDD_ADD                         155
#define IDD_CHANGEDFILES                158
#define IDD_SIMPLEPROMPT                160
#define IDD_INPUTDLG                    161
#define IDR_SEARCH                      163
#define IDI_DRIVES                      164
#define IDD_URL                         164
#define IDI_SSH                         165
#define IDI_PROXY                       166
#define IDI_MISC                        167
#define IDB_LOGOFLIPPED                 168
#define IDB_TTF_BMP                     169
#define IDD_SETTINGSPROGSADV            170
#define IDD_TOOLASSOC                   171
#define IDD_CHECKFORUPDATES             174
#define IDD_REVERT                      175
#define IDD_STATGRAPH                   179
#define IDD_PATCH_FILE_OPEN_CUSTOM      180
#define IDD_SETOVERLAYICONS             184
#define IDI_SET_OVERLAYS                190
#define IDD_SETTINGSPROGSDIFF           192
#define IDD_SETTINGSPROGSMERGE          193
#define IDD_SETTINGSLOOKANDFEEL         195
#define IDI_GENERAL                     195
#define IDD_SETTINGSDIALOGS             196
#define IDI_LOOKANDFEEL                 196
#define IDI_ICONSET                     197
#define IDD_SETTINGSDIALOGS2            197
#define IDI_DIALOGS                     198
#define IDD_DIFFFILES                   199
#define IDD_RESOLVE                     207
#define IDI_WARNING_GENERAL             210
#define IDD_HISTORYDLG                  211
#define IDR_CLEANUPANI                  212
#define IDD_SETTINGSCOLORS_2            212
#define IDI_ACTIONADDED                 213
#define IDI_ACTIONDELETED               214
#define IDI_ACTIONMODIFIED              215
#define IDI_ACTIONREPLACED              216
#define IDI_SAVEDDATA                   225
#define IDI_GRAPHBAR                    229
#define IDI_GRAPHBARSTACKED             230
#define IDI_GRAPHLINE                   231
#define IDI_GRAPHLINESTACKED            232
#define IDI_GRAPHPIE                    233
#define IDI_SWITCHLEFTRIGHT             234
#define IDR_STATGRAPH                   235
#define IDD_SETTINGSHOOKCONFIG          236
#define IDI_HOOK                        237
#define IDD_EXPORT                      238
#define IDD_INPUTLOGDLG                 241
#define IDD_CREATECHANGELIST            243
#define IDI_REPOBROWSER_BKG             244
#define IDD_SETTINGSTBLAME              244
#define IDC_PANCUR                      250
#define IDC_PANCURDOWN                  251
#define IDC_RENINFOLABEL                252
#define IDI_TORTOISEBLAME               252
#define IDR_ACC_LOGDLG                  254
#define IDI_ADD_BKG                     255
#define IDI_RESOLVE_BKG                 256
#define IDI_REVERT_BKG                  257
#define IDI_COMMIT_BKG                  258
#define IDI_CFM_BKG                     260
#define IDR_DOWNLOAD                    263
#define IDI_CANCELNORMAL                264
#define IDI_CANCELPRESSED               265
#define IDI_LOGFILTER                   266
#define IDI_FILTEREDIT                  267
#define IDI_COPY_BKG                    270
#define IDI_EXPORT_BKG                  271
#define IDI_IMPORT_BKG                  272
#define IDI_MERGE_BKG                   273
#define IDI_RENAME_BKG                  274
#define IDI_SWITCH_BKG                  275
#define IDD_SETTINGSBUGTRAQ             283
#define IDI_BUGTRAQ                     284
#define IDD_SETTINGSBUGTRAQADV          284
#define IDI_UP                          286
#define IDI_MKDIR                       289
#define IDI_REFRESH                     290
#define IDI_SAVE                        291
#define IDI_SAVEAS                      292
#define IDI_EXPLORER                    293
#define IDI_OPEN                        294
#define IDI_UPDATE_BKG                  295
#define IDD_CLONE                       297
#define IDB_GIT                         299
#define IDD_GITPROGRESS                 300
#define IDD_PULLFETCH                   302
#define IDD_PUSH                        303
#define IDD_GITSWITCH                   304
#define IDD_AUTOTEXTTESTDLG             306
#define IDD_NEW_BRANCH_TAG              309
#define IDD_APPLY_PATCH_LIST            311
#define IDD_FORMAT_PATCH                312
#define IDD_MERGE                       313
#define IDD_SETTINGSCOLORS_1            315
#define IDD_SETTINGSCOLORS_3            316
#define IDD_RESET                       317
#define IDD_REBASE                      318
#define IDI_GITCONFIG                   319
#define IDI_GITREMOTE                   320
#define IDD_SENDMAIL                    320
#define IDD_SETTINGSMTP                 321
#define IDD_DIALOG_BROWSE_REFS          322
#define IDD_ADD_REMOTE                  323
#define IDR_ACC_COMMITDLG               325
#define IDD_SYNC                        326
#define IDI_SHOWBRANCHES                326
#define IDD_BUGTRAQREGEXTESTER          327
#define IDD_PATCH_VIEW                  328
#define IDD_SVNIGNORE                   329
#define IDD_CREATEREPO                  330
#define IDD_SVNDCOMMITTYPE              331
#define IDI_ACTIONFETCHING              332
#define IDD_SETTINGSPROGSALTERNATIVEEDITOR 333
#define IDD_REQUESTPULL                 334
#define IDB_BITMAP_REFTYPE              336
#define IDI_IMPORTPATHCES_BKG           337
#define IDD_SETTINGSOVERLAYHANDLERS     338
#define IDI_LIBRARY                     339
#define IDD_SETTINGS_CONFIG             340
#define IDI_RESTORE                     341
#define IDI_RESTOREOVL                  342
#define IDI_JUMPUP                      343
#define IDI_JUMPDOWN                    344
#define IDD_LOGORDERING                 345
#define IDI_GITCREDENTIAL               346
#define IDI_EXTERNALOVL                 347
#define IDI_MERGEACTIVE                 348
#define IDI_EXECUTABLEOVL               349
#define IDI_SYMLINKOVL                  350
#define IDI_SPELL                       351
#define IDI_FILE                        352
#define IDI_CODE                        353
#define IDI_SNIPPET                     354
#define IDI_CERTCHECK                   355
#define IDD_SETTINGSUDIFF               357
#define IDC_LOGLIST                     1003
#define IDC_PASSEDIT                    1004
#define IDC_INFOTEXT                    1005
#define IDC_EXPORTFILE                  1010
#define IDC_SVNPROGRESS                 1013
#define IDC_LOGMESSAGE                  1014
#define IDC_LOGMSG                      1015
#define IDC_EXTDIFF                     1015
#define IDC_EXTMERGE                    1016
#define IDC_DIFFVIEWER                  1017
#define IDC_EXTDIFFBROWSE               1021
#define IDC_EXTMERGEBROWSE              1022
#define IDC_ENABLE                      1023
#define IDC_SAVECHECK                   1023
#define IDS_APPNAME                     1026
#define IDC_NAME                        1027
#define IDC_SERVERADDRESS               1027
#define IDC_USEREDIT                    1027
#define IDC_URLCOMBO                    1029
#define IDC_FONTNAMES                   1030
#define IDC_LOGBUTTON                   1031
#define IDC_UPDATE                      1031
#define IDC_DONOTASKAGAIN               1032
#define IDC_EXPORTFILE_BROWSE           1036
#define IDC_INCLUDEPATHS                1036
#define IDC_SERVERPORT                  1038
#define IDS_SUCCESS                     1038
#define IDC_USERNAME                    1039
#define IDS_FAIL                        1039
#define IDC_PASSWORD                    1040
#define IDS_DONE                        1040
#define IDC_FILELIST                    1043
#define IDC_ADDLIST                     1043
#define IDC_CHANGEDLIST                 1043
#define IDC_MENULIST                    1043
#define IDC_REVERTLIST                  1043
#define IDS_OKBUTTON                    1043
#define IDC_LANGUAGECOMBO               1044
#define IDC_COMMIT_TO                   1046
#define IDC_REMOVABLE                   1048
#define IDC_COMMIT_AUTHORDATA           1048
#define IDC_NETWORK                     1049
#define IDC_FIXED                       1050
#define IDC_CDROM                       1051
#define IDC_VERSIONABOUT                1054
#define IDC_UNKNOWN                     1061
#define IDC_INPUTTEXT                   1064
#define IDC_HINTTEXT                    1065
#define IDC_SELECTALL                   1067
#define IDC_SSHCLIENT                   1068
#define IDC_INCLUDE_IGNORED             1068
#define IDC_SSHBROWSE                   1069
#define IDS_COMMITBUTTON                1070
#define IDC_RELATIVETIMES               1072
#define IDC_RAM                         1073
#define IDC_CHECKNEWERVERSION           1073
#define IDC_SHOWUNVERSIONED             1073
#define IDC_RIGHTSIDEBRANCHESTAGS       1073
#define IDC_EXPORTFILE_LABEL            1074
#define IDC_ASTERISKLOGPREFIX           1074
#define IDC_VERSIONBOX                  1075
#define IDC_LABEL                       1076
#define IDC_MSGVIEW                     1077
#define IDC_BUGID                       1077
#define IDC_EXCLUDEPATHS                1077
#define IDC_DRIVEGROUP                  1079
#define IDC_PROXYGROUP                  1080
#define IDC_SSHGROUP                    1081
#define IDC_COMMITGROUP                 1083
#define IDC_WEBLINK                     1084
#define IDC_SUPPORTLINK                 1085
#define IDC_FONTSIZES                   1086
#define IDC_ONLYEXPLORER                1088
#define IDC_DIFFVIEWERBROWSE            1089
#define IDC_EXTDIFFADVANCED             1090
#define IDC_EXTDIFF_OFF                 1091
#define IDC_EXTDIFF_ON                  1092
#define IDC_EXTMERGEADVANCED            1093
#define IDC_EXTMERGE_OFF                1094
#define IDC_EXTMERGE_ON                 1095
#define IDC_DIFFVIEWER_OFF              1096
#define IDC_DIFFVIEWER_ON               1097
#define IDC_ADDTOOL                     1098
#define IDC_EDITTOOL                    1099
#define IDC_REMOVETOOL                  1100
#define IDC_TOOLLISTCTRL                1101
#define IDC_EXTEDIT                     1102
#define IDC_TOOLEDIT                    1103
#define IDC_TOOLBROWSE                  1104
#define IDC_SHORTDATEFORMAT             1105
#define IDC_SUMMARYTEXT                 1106
#define IDC_STATISTICS                  1108
#define IDC_TEXT_INFO                   1109
#define IDC_COMMITLABEL                 1110
#define IDC_PROGRESS                    1111
#define IDC_YOURVERSION                 1112
#define IDC_CURRENTVERSION              1113
#define IDC_CHECKRESULT                 1114
#define IDC_SOURCE                      1115
#define IDC_BUGIDLABEL                  1119
#define IDC_ICONSETCOMBO                1124
#define IDC_KEEPLISTS                   1126
#define IDC_SHOWEXCLUDEDASNORMAL        1126
#define IDC_SORTBYCOMMITCOUNT           1126
#define IDC_DIFFBYDOUBLECLICK           1127
#define IDC_ABBREVIATERENAMINGS         1128
#define IDC_CHECK_UNTRACKED             1130
#define IDC_GRAPH                       1131
#define IDC_CHECK_ALL                   1131
#define IDC_STATBUTTON                  1132
#define IDC_PATCH_TO_CLIPBOARD          1132
#define IDC_LOG                         1132
#define IDC_GRAPHCOMBO                  1133
#define IDC_GRAPHTYPELABEL              1134
#define IDC_COMMITSEACHWEEK             1135
#define IDC_MOSTACTIVEAUTHOR            1136
#define IDC_LEASTACTIVEAUTHOR           1137
#define IDC_FILECHANGESEACHWEEK         1138
#define IDC_COMMITSEACHWEEKAVG          1140
#define IDC_COMMITSEACHWEEKMIN          1141
#define IDC_COMMITSEACHWEEKMAX          1142
#define IDC_MOSTACTIVEAUTHORAVG         1143
#define IDC_MOSTACTIVEAUTHORMIN         1144
#define IDC_MOSTACTIVEAUTHORMAX         1145
#define IDC_LEASTACTIVEAUTHORAVG        1146
#define IDC_LEASTACTIVEAUTHORMIN        1147
#define IDC_LEASTACTIVEAUTHORMAX        1148
#define IDC_FILECHANGESEACHWEEKAVG      1149
#define IDC_FILECHANGESEACHWEEKMIN      1150
#define IDC_FILECHANGESEACHWEEKMAX      1151
#define IDS_MSGBOX_HELP                 1152
#define IDS_MSGBOX_DONOTSHOWAGAIN       1153
#define IDS_MSGBOX_ABORT                1154
#define IDS_MSGBOX_RETRY                1155
#define IDC_MOSTACTIVEAUTHORNAME        1155
#define IDS_MSGBOX_IGNORE               1156
#define IDC_LEASTACTIVEAUTHORNAME       1156
#define IDS_MSGBOX_CANCEL               1157
#define IDC_AVG                         1157
#define IDS_MSGBOX_TRYAGAIN             1158
#define IDC_MIN                         1158
#define IDS_MSGBOX_CONTINUE             1159
#define IDC_MAX                         1159
#define IDS_MSGBOX_OK                   1160
#define IDC_NUMWEEK                     1160
#define IDS_MSGBOX_YES                  1161
#define IDC_NUMAUTHOR                   1161
#define IDS_MSGBOX_NO                   1162
#define IDC_NUMCOMMITS                  1162
#define IDC_NUMFILECHANGES              1163
#define IDC_NUMWEEKVALUE                1164
#define IDC_NUMAUTHORVALUE              1165
#define IDC_NUMCOMMITSVALUE             1166
#define IDC_NUMFILECHANGESVALUE         1167
#define IDC_ICONSETLABEL                1170
#define IDC_ICONLIST                    1171
#define IDC_LISTRADIO                   1172
#define IDC_SYMBOLRADIO                 1173
#define IDC_AUTOCLOSECOMBO              1181
#define IDS_ERR_INVALIDPATH             1183
#define IDC_AUTOCOMPLETION              1184
#define IDC_SPLITTERTOP                 1191
#define IDC_SPLITTERBOTTOM              1192
#define IDC_SEARCHEDIT                  1194
#define IDC_DATETO                      1198
#define IDC_DATEFROM                    1199
#define IDC_FROMLABEL                   1200
#define IDC_TOLABEL                     1201
#define IDC_WHOLE_PROJECT               1203
#define IDC_CHECKBOX                    1207
#define IDC_SHOWWHOLEPROJECT            1208
#define IDC_SHOWUNMODIFIED              1209
#define IDC_CHECKNEWERBUTTON            1215
#define IDC_MSYSGIT_CHECK               1216
#define IDC_REALM                       1220
#define IDC_AUTOCOMPLETIONTIMEOUT       1221
#define IDC_AUTOCOMPLETIONTIMEOUTLABEL  1222
#define IDC_RESOLVELIST                 1231
#define IDC_EXTERNALWARNING             1238
#define IDC_MERGEACTIVE                 1239
#define IDC_MESSAGEGROUP                1241
#define IDC_LISTGROUP                   1242
#define IDC_PROGRESSBAR                 1243
#define IDC_PROGRESSLABEL               1244
#define IDC_HISTORYLIST                 1245
#define IDC_HISTORY                     1246
#define IDC_CONFLICTCOLOR               1249
#define IDC_ADDEDCOLOR                  1250
#define IDC_DELETEDCOLOR                1251
#define IDC_MERGEDCOLOR                 1252
#define IDC_MODIFIEDCOLOR               1253
#define IDC_RESTORE                     1254
#define IDC_NOTENODECOLOR               1256
#define IDC_RENAMEDCOLOR                1257
#define IDC_SKIPPER                     1261
#define IDC_SKIPPERLABEL                1262
#define IDC_SHOWIGNORED                 1264
#define IDC_AUTHORSCASESENSITIVE        1265
#define IDC_SHOWLOCALCHANGESIGNORED     1265
#define IDC_MAXHISTORY                  1268
#define IDC_CACHEDEFAULT                1269
#define IDC_CACHESHELL                  1270
#define IDC_CACHESHELL2                 1271
#define IDC_CACHENONE                   1272
#define IDS_MSGBOX_DONOTSHOW            1272
#define IDC_URLHISTORY                  1272
#define IDC_URLHISTCLEAR                1273
#define IDC_LOGHISTORY                  1274
#define IDC_LOGHISTCLEAR                1275
#define IDC_RESIZABLEHISTCLEAR          1276
#define IDC_RESIZABLEHISTORY            1277
#define IDC_AUTHHISTORY                 1278
#define IDC_AUTHHISTCLEAR               1279
#define IDC_HOOKADDBUTTON               1279
#define IDC_BUGTRAQADDBUTTON            1279
#define IDC_BUTTON_TABCTRL              1279
#define IDC_REPOLOG                     1280
#define IDC_REPOLOGCLEAR                1281
#define IDC_GRAPHBARBUTTON              1297
#define IDC_GRAPHBARSTACKEDBUTTON       1298
#define IDC_GRAPHLINEBUTTON             1299
#define IDC_GRAPHLINESTACKEDBUTTON      1300
#define IDC_GRAPHPIEBUTTON              1301
#define IDC_FIRSTURL                    1301
#define IDC_DIFFSTATIC1                 1302
#define IDC_SUBMODULEDIFFTITLE          1302
#define IDC_SECONDURL                   1303
#define IDC_SWITCHLEFTRIGHT             1307
#define IDC_SPLITTER                    1312
#define IDC_UNVERSIONEDASMODIFIED       1313
#define IDC_RECURSIVESUBMODULES         1314
#define IDC_FLOPPY                      1315
#define IDC_MAXHISTORYLABEL             1317
#define IDC_HOOKPATH                    1323
#define IDC_HOOKBROWSE                  1324
#define IDC_HOOKCOMMANDLINE             1325
#define IDC_HIDECHECK                   1326
#define IDS_ERR_TEXTVIEWSTART           1326
#define IDC_WAITCHECK                   1327
#define IDC_HOOKTYPECOMBO               1329
#define IDC_HOOKLIST                    1330
#define IDC_HOOKEDITBUTTON              1331
#define IDC_HOOKREMOVEBUTTON            1332
#define IDC_HOOKCOMMANDBROWSE           1333
#define IDC_HOOKTYPELABEL               1334
#define IDC_HOOKWCPATHLABEL             1335
#define IDC_HOOKCMLABEL                 1336
#define IDC_LOGINFO                     1337
#define IDC_REV1BTN                     1353
#define IDC_REV2BTN                     1354
#define IDC_REV1BTN2                    1354
#define IDC_RESETFILTER                 1355
#define IDC_ACTIONLABEL                 1356
#define IDC_GROUPBOX                    1359
#define IDC_HOOKCOPYBUTTON              1367
#define IDC_INFOLABEL                   1368
#define IDC_REPOTREE                    1371
#define IDC_REPOLIST                    1372
#define IDC_BUGTRAQLIST                 1372
#define IDC_LIST_PATCH                  1372
#define IDC_COMMIT_LIST                 1372
#define IDC_LIST_REMOTE                 1372
#define IDC_LIST_REF_LEAFS              1372
#define IDC_NEWLINESCOLOR               1378
#define IDC_OLDLINESCOLOR               1380
#define IDC_TABSIZE                     1381
#define IDC_REFRESH                     1382
#define IDC_ACTIONLOGSHOW               1382
#define IDC_BUGTRAQEDITBUTTON           1382
#define IDC_BUGTRAQBUTTON               1382
#define IDC_RESTOREDEFAULTS             1382
#define IDC_OPTIONS                     1382
#define IDC_CLONE_BROWSE_URL            1382
#define IDC_BUTTON_SHOW                 1382
#define IDC_BUTTON_ADD                  1382
#define IDC_REMOTE_MANAGE               1382
#define IDC_PROGRESS_BUTTON1            1382
#define IDC_BUTTON_LOCAL_BRANCH         1382
#define IDC_EDITGLOBALGITCONFIG         1382
#define IDC_BUTTON_SHOW_ENV             1382
#define IDC_SHOW_MODIFIED_FILES         1383
#define IDC_REPOGROUP                   1383
#define IDC_CLONE_DIR_BROWSE            1383
#define IDC_BUTTON_TO                   1383
#define IDC_BUTTON_UP                   1383
#define IDC_REBASE_POST_BUTTON          1383
#define IDC_BUTTON_REMOTE_BRANCH        1383
#define IDC_EDITLOCALGITCONFIG          1383
#define IDC_COMMIT                      1383
#define IDC_BUTTON_BAD                  1383
#define IDC_BUTTON_DIR                  1384
#define IDC_BUTTON_DOWN                 1384
#define IDC_PUTTYKEYFILE_BROWSE         1384
#define IDC_BUTTON_UP2                  1384
#define IDC_BUTTON_STASH                1384
#define IDC_EDITSYSTEMGITCONFIG         1384
#define IDC_FROMGROUP                   1385
#define IDC_BUTTON_REMOVE               1385
#define IDC_BUTTON_DOWN2                1385
#define IDC_CONFIG                      1385
#define IDC_BUTTON_UNIFIEDDIFF          1385
#define IDC_FILTER                      1387
#define IDC_SELECTFILESONCOMMIT         1405
#define IDC_STRIPCOMMENTEDLINES         1406
#define IDC_PROXYLABEL1                 1409
#define IDC_PROXYLABEL2                 1410
#define IDC_PROXYLABEL3                 1411
#define IDC_PROXYLABEL6                 1414
#define IDC_SYSTEMLOCALEFORDATES        1426
#define IDC_ACTIONLOGCLEAR              1427
#define IDC_MAXLINES                    1428
#define IDC_SHOWIGNOREDOVERLAY          1432
#define IDC_USERECYCLEBIN               1432
#define IDC_SHOWUNVERSIONEDOVERLAY      1462
#define IDC_LINK                        1466
#define IDC_BUGTRAQPARAMETERS           1469
#define IDC_CLONE_DIR                   1469
#define IDC_BUGTRAQREMOVEBUTTON         1470
#define IDC_GIT_USEREMAIL               1470
#define IDC_EDIT_REMOTE                 1470
#define IDC_SMTP_PORT                   1470
#define IDC_EDIT_SVN_FROM               1470
#define IDC_REV2EDIT                    1470
#define IDC_NEWBRANCH                   1470
#define IDC_BUGTRAQCOPYBUTTON           1471
#define IDC_GIT_USERESINGNINGKEY        1471
#define IDC_BUGTRAQWCPATHLABEL          1472
#define IDC_BUGTRAQPATH                 1473
#define IDC_BUGTRAQBROWSE               1474
#define IDC_BUGTRAQPROVIDERLABEL        1475
#define IDC_BUGTRAQPROVIDERCOMBO        1476
#define IDC_BUGTRAQPARAMETERSLABEL      1477
#define IDC_BROWSEREFS_EDIT_FILTER      1478
#define IDC_BROWSEREFS_STATIC_FILTER    1479
#define IDC_FORCE                       1480
#define IDC_UNVERSIONEDITEMS            1481
#define IDC_CHECK_NOFF                  1481
#define IDC_SENDMAIL_COMBINE            1481
#define IDC_PUSHALL                     1481
#define IDC_SIGN_OFF                    1482
#define IDC_SIGNOFF                     1482
#define IDC_CHECK_NOCOMMIT              1482
#define IDC_PROC_PUSH_SET_PUSHREMOTE    1482
#define IDC_BUTTON_BROWSE               1483
#define IDC_BUTTON_BROWSE_SOURCE_BRANCH 1483
#define IDC_BUTTON_BROWSE_REF           1483
#define IDC_BUTTON_MANAGE               1483
#define IDC_KEEP_CR                     1483
#define IDC_BUTTON_BROWSE_DEST_BRANCH   1484
#define IDC_CHECK_FFONLY                1484
#define IDC_TITLE_ANIMATE               1485
#define IDC_CHECK_FETCHTAGS             1485
#define IDC_PROC_PUSH_SET_PUSHBRANCH    1485
#define IDC_RUN_PROGRESS                1486
#define IDC_PROC_PUSH_SET_UPSTREAM      1486
#define IDC_CURRENT                     1487
#define IDC_STATIC_RECURSE_SUBMODULES   1487
#define IDC_COMBOBOX_RECURSE_SUBMODULES 1488
#define IDC_REMOTE_COMBO                1489
#define IDC_BRANCH_REMOTE               1489
#define IDC_COMBOBOXEX_BRANCH           1489
#define IDC_COMBOBOXEX_FROM             1489
#define IDC_REMOTE_RD                   1490
#define IDC_URL                         1490
#define IDC_COMBOBOXEX_TAGS             1490
#define IDC_COMBOBOXEX_TO               1490
#define IDC_COMBOBOXEX_VERSION          1491
#define IDC_OTHER_RD                    1492
#define IDC_OTHER                       1493
#define IDC_BRANCH_SOURCE               1493
#define IDC_REMOTE_BRANCH               1494
#define IDC_RD_REMOTE                   1494
#define IDC_RD_URL                      1495
#define IDC_COLOR_LINE7                 1495
#define IDC_REMOTE                      1496
#define IDC_PACK                        1497
#define IDC_FORCE_WITH_LEASE            1498
#define IDC_TAGS                        1499
#define IDC_BRANCH_GROUP                1500
#define IDC_COLOR_LINE8                 1500
#define IDC_URL_GROUP                   1501
#define IDC_OPTION_GROUP                1502
#define IDC_STATIC_REMOTE               1503
#define IDC_STATIC_SOURCE               1504
#define IDC_PUTTYKEY_AUTOLOAD           1505
#define IDS_CHANGETYPE                  1506
#define IDC_SENDMAIL_SUBJECT            1510
#define IDC_SMTP_PASSWORD               1510
#define IDC_BUGTRAQ_LABEL               1510
#define IDC_CHECK_SVN_BRANCH            1510
#define IDC_RADIO_HEAD                  1511
#define IDC_BUGTRAQ_LOGREGEX            1511
#define IDC_EDIT_SVN_TAG                1511
#define IDC_RADIO_BRANCH                1512
#define IDC_EDIT_SVN_BRANCH             1512
#define IDC_RADIO_TAGS                  1513
#define IDC_CHECK_SVN_TAG               1513
#define IDC_RADIO_VERSION               1514
#define IDC_GROUP_BRANCH                1515
#define IDC_GROUP_OPTION                1517
#define IDC_LABEL_BRANCH                1518
#define IDC_BRANCH_TAG                  1519
#define IDC_AUTOTEXTCONTENT             1520
#define IDC_CHECK_TRACK                 1520
#define IDC_AUTOTEXTREGEX               1521
#define IDC_CHECK_FORCE                 1521
#define IDC_AUTOTEXTSCAN                1522
#define IDC_GROUP_BASEON                1522
#define IDC_TESTRESULT                  1523
#define IDC_CHECK_BRANCHOVERRIDE        1523
#define IDC_CHECK_SIGN                  1523
#define IDC_TIMINGLABEL                 1524
#define IDC_CHECK_SQUASH                1524
#define IDC_CHECK_SWITCH                1525
#define IDC_CHECK_MERGE                 1526
#define IDC_CHECK_BRANCH                1527
#define IDC_EDIT_BRANCH                 1528
#define IDC_SHOWLOCKEDOVERLAY           1529
#define IDC_EDIT_ORIGIN                 1530
#define IDC_CHECK_ORIGIN                1531
#define IDS_ALLREFS                     1531
#define IDC_RADIO_SINCE                 1532
#define IDC_COMBOBOXEX_SINCE            1533
#define IDC_RADIO_NUM                   1534
#define IDC_RADIO_RANGE                 1535
#define IDC_SPIN_NUM                    1536
#define IDC_COMBOBOXEX_DIR              1537
#define IDC_GROUP_DIR                   1538
#define IDC_GROUP_VERSION               1539
#define IDC_EDIT_NUM                    1540
#define IDC_BUTTON_FROM                 1541
#define IDC_CURRENT_BRANCH              1542
#define IDC_BUTTON_REF                  1542
#define IDC_REGEDT                      1542
#define IDC_LOCAL_BRANCH                1543
#define IDC_LOCAL_BRANCHES              1543
#define IDC_COLOR_LINE5                 1544
#define IDC_COLOR_LINE6                 1545
#define IDC_COLOR_LINE1                 1546
#define IDC_COLOR_LINE2                 1547
#define IDC_COLOR_LINE3                 1548
#define IDC_SHOWREADONLYOVERLAY         1550
#define IDC_MSYSGIT_PATH                1550
#define IDC_RADIO_RESET_SOFT            1550
#define IDC_SHOWDELETEDOVERLAY          1551
#define IDC_MSYSGIT_BROWSE              1551
#define IDC_RADIO_RESET_MIXED           1551
#define IDC_BORDER                      1551
#define IDC_KEEPFILELISTSENGLISH        1552
#define IDC_MSYSGIT_VER                 1552
#define IDC_RADIO_RESET_HARD            1552
#define IDC_GROUP_RESET_TYPE            1554
#define IDC_COMMIT_AMEND                1555
#define IDC_COMMIT_AMENDDIFF            1556
#define IDC_REBASE_PROGRESS             1557
#define IDC_COMMIT_SETDATETIME          1557
#define IDC_COMMIT_SETAUTHOR            1558
#define IDC_SPLITALLOPTIONS             1559
#define IDC_REBASE_SPLIT                1562
#define IDC_STATUS_STATIC               1563
#define IDC_REBASE_CONTINUE             1564
#define IDC_REBASE_ABORT                1565
#define IDC_REBASE_DUMY_TAB             1566
#define IDC_GIT_USERNAME                1566
#define IDC_EDIT_URL                    1568
#define IDC_EDIT_PUTTY_KEY              1569
#define IDC_BUGTRAQLOGREGEX1            1569
#define IDC_BUGTRAQLOGREGEX2            1570
#define IDC_PUTTYKEYFILE                1571
#define IDC_GROUP_CLONE                 1572
#define IDC_GROUPT_REMOTE               1573
#define IDC_SENDMAIL_PATCHS             1575
#define IDC_SENDMAIL_TO                 1577
#define IDC_COMBOBOXEX_REF              1578
#define IDC_SENDMAIL_CC                 1578
#define IDC_REGEXIDLABEL                1578
#define IDC_STATIC_REF                  1579
#define IDC_SENDMAIL_ATTACHMENT         1579
#define IDC_REGEXMSGLABEL               1579
#define IDC_REFLOG_LIST                 1580
#define IDC_SENDMAIL_SETUP              1580
#define IDC_STATIC_REPOURL              1580
#define IDC_IBUGTRAQPROVIDERGROUP       1580
#define IDC_COMBOBOXEX_REPOSITORY       1581
#define IDC_UUIDLABEL32                 1581
#define IDC_COMBOBOXEX_PATH             1582
#define IDC_SENDMAIL_GROUP              1582
#define IDC_UUID32                      1582
#define IDC_REP_BROWSE                  1583
#define IDC_SEND_ADDRESS                1583
#define IDC_UUIDLABEL64                 1583
#define IDC_BUTTON_PATH_BROWSE          1584
#define IDC_SMTP_SERVER                 1584
#define IDC_UUID64                      1584
#define IDC_GROUP_SUBMODULE             1585
#define IDC_SMTP_AUTH                   1585
#define IDC_PARAMS                      1585
#define IDC_BRANCH_CHECK                1586
#define IDC_SMTP_USER                   1586
#define IDC_PARAMSLABEL                 1586
#define IDC_SUBMODULE_BRANCH            1587
#define IDC_CHECK_SENDMAIL              1587
#define IDD_REFLOG                      1588
#define IDC_TREE_REF                    1588
#define IDD_SUBMODULE_ADD               1589
#define IDC_EDIT_NAME                   1589
#define IDC_BUGTRAQ_WARNINGIFNOISSUE    1593
#define IDC_BUGTRAQ_APPEND              1594
#define IDC_WARN_NO_SIGNED_OFF_BY       1594
#define IDC_BUGTRAQ_NUMBER              1595
#define IDC_BUGTRAQ_URL                 1599
#define IDC_BUGTRAQ_MESSAGE             1600
#define IDC_CHECK_REBASE                1602
#define IDC_LANGCOMBO                   1602
#define IDC_CLONE_GROUP_SVN             1603
#define IDC_CHECK_PRUNE                 1603
#define IDC_CHECK_SVN                   1604
#define IDC_CHECK_SVN_TRUNK             1605
#define IDC_EDIT_SVN_TRUNK              1606
#define IDC_REBASE_CHECK_FORCE          1607
#define IDC_EDIT_DEPTH                  1607
#define IDC_CHECK_SVN_FROM              1608
#define IDC_HANDLERHINT                 1609
#define IDC_COMBOBOXEX_URL              1610
#define IDC_BUTTON_PULL                 1611
#define IDC_BUTTON_PUSH                 1612
#define IDC_SAMPLELABEL                 1612
#define IDC_BUTTON_APPLY                1613
#define IDC_BUTTON_EMAIL                1614
#define IDC_STATIC_LOCAL_BRANCH         1616
#define IDC_STATIC_REMOTE_BRANCH        1617
#define IDC_STATIC_REMOTE_URL           1618
#define IDC_CHECK_PUTTY_KEY             1619
#define IDC_STATIC_STATUS               1621
#define IDC_PROGRESS_SYNC               1622
#define IDC_ANIMATE_SYNC                1623
#define IDC_GROUP_INFO                  1624
#define IDC_BUTTON_COMMIT               1625
#define IDC_CHECK_DIR                   1626
#define IDC_RADIO_CLEAN_ALL             1627
#define IDC_RADIO_CLEAN_NO              1628
#define IDC_RADIO_CLEAN_IGNORE          1629
#define IDC_GROUP_CLEAN_TYPE            1630
#define IDC_CHECK_AUTOCRLF              1631
#define IDC_COMBO_SAFECRLF              1632
#define IDC_CHECK_QUOTEPATH             1633
#define IDC_STATIC_MERGE_MESSAGE        1635
#define IDC_PATCH                       1636
#define IDC_VIEW_PATCH                  1637
#define IDC_BUTTON_SUBMODULE            1639
#define IDC_RADIO_EXCLUDE               1640
#define IDC_RADIO_GITIGNORE             1641
#define IDC_GROUP_TYPE                  1642
#define IDC_REV1EDIT                    1643
#define IDC_REV1GROUP                   1644
#define IDC_REV2GROUP                   1645
#define IDC_CHECK_DEPTH                 1646
#define IDC_EDIT_MESSAGE                1647
#define IDC_GROUP_MESSAGE               1648
#define IDC_STATIC_REMINDER             1649
#define IDC_CHECK_USERNAME              1650
#define IDC_EDIT_USERNAME               1651
#define IDC_MSYSGIT_EXTERN_PATH         1652
#define IDC_CHECK_BARE                  1653
#define IDC_INIT_REPO_DESC              1654
#define IDC_CHECK_RECURSIVE             1654
#define IDC_CHECK_3WAY                  1656
#define IDC_CHECK_IGNORE_SPACE          1657
#define IDC_AM_SPLIT                    1658
#define IDC_AM_DUMY_TAB                 1659
#define IDC_REMEMBER                    1660
#define IDC_HIDEMENUS                   1660
#define IDC_ALTERNATIVEEDITOR_OFF       1661
#define IDC_ALTERNATIVEEDITOR_ON        1662
#define IDC_ALTERNATIVEEDITOR           1663
#define IDC_ALTERNATIVEEDITORBROWSE     1664
#define IDC_NOAUTOSELECTSUBMODULES      1669
#define IDC_COMMIT_DATEPICKER           1670
#define IDC_COMMIT_TIMEPICKER           1671
#define IDC_COMBOBOXEX_GOOD             1671
#define IDC_BUTTON_GOOD                 1672
#define IDC_GROUP_STASHMESSAGE          1673
#define IDC_STASHMESSAGE                1674
#define IDC_FOLLOWRENAMES               1675
#define IDC_TOGROUP                     1676
#define IDC_IGNORE_WHITESPACE           1676
#define IDC_FROMHASH                    1677
#define IDC_FROMSUBJECT                 1678
#define IDC_TOHASH                      1679
#define IDC_TOSUBJECT                   1680
#define IDC_CHECK_NEWBRANCH             1681
#define IDC_TOGROUP2                    1681
#define IDC_CHECK_CHERRYPICKED_FROM     1682
#define IDC_THEIRSHASH                  1682
#define IDC_CREATELIB                   1683
#define IDC_THEIRSSUBJECT               1683
#define IDC_BUTTON_REVISION             1684
#define IDC_REPOBROWSER_URL             1685
#define IDC_REFLOG_BUTTONCLEARSTASH     1686
#define IDC_GROUP_IGNORE_TYPE           1686
#define IDC_RADIO_IGNORETYPE_ONLYINFOLDER 1687
#define IDC_RADIO_IGNORETYPE_RECURSIVELY 1688
#define IDC_RADIO_IGNOREFILE_GLOBALGITIGNORE 1689
#define IDC_RADIO_IGNOREFILE_LOCALGITIGNORES 1690
#define IDC_RADIO_IGNOREFILE_GITINFOEXCLUDE 1691
#define IDC_GROUP_IGNORE_FILE           1692
#define IDC_CHECK_SUBMODULE_INIT        1693
#define IDC_CHECK_SUBMODULE_RECURSIVE   1694
#define IDC_LOG2                        1695
#define IDC_LIST_TAGS                   1696
#define IDC_SHOW_DIFF                   1696
#define IDC_GROUP_CHANGELOG             1697
#define IDC_GROUP_DOWNLOADS             1698
#define IDC_LOG3                        1698
#define IDC_SELECTLABEL                 1700
#define IDS_ABOUTVERSION                1700
#define IDC_CHECKALL                    1701
#define IDC_CHECKNONE                   1702
#define IDC_CHECKUNVERSIONED            1703
#define IDC_CHECKVERSIONED              1704
#define IDC_CHECKADDED                  1705
#define IDC_CHECKMODIFIED               1706
#define IDC_CHECKFILES                  1707
#define IDC_CHECKSUBMODULES             1708
#define IDC_CHECKDELETED                1709
#define IDC_BUTTON_UPDATE               1710
#define IDC_LIST_DOWNLOADS              1711
#define IDC_STATIC_REVISION             1712
#define IDC_STATIC_REVISION2            1713
#define IDC_STATIC_SUBJECT              1714
#define IDC_STATIC_SUBJECT2             1715
#define IDC_CHECK_NOCHECKOUT            1716
#define IDC_STATIC_REVISION3            1716
#define IDC_VIEWSYSTEMGITCONFIG         1717
#define IDC_STATIC_SUBJECT3             1717
#define IDC_EDITGLOBALXDGGITCONFIG      1718
#define IDC_COMMIT_MESSAGEONLY          1719
#define IDC_STATIC_CHANGETYPE           1720
#define IDC_CHANGETYPE                  1721
#define IDC_GROUP                       1722
#define IDC_STATIC_CHANGETYPE2          1722
#define IDC_LOG_JUMPTYPE                1723
#define IDC_THEIRSCHANGETYPE            1723
#define IDC_LOG_JUMPUP                  1724
#define IDC_LOG_JUMPDOWN                1725
#define IDC_TEMPFILESCLEAR              1726
#define IDC_STATIC_TAGOPT               1727
#define IDC_COMBO_TAGOPT                1728
#define IDC_REV1BTN1                    1729
#define IDC_CHECK_NORECYCLEBIN          1730
#define IDC_CHECK_DRYRUN                1731
#define IDC_SYMBOLIZEREFNAMES           1733
#define IDC_CHECK_SUBMODULE_NOFETCH     1734
#define IDC_CHECK_SUBMODULE_MERGE       1735
#define IDC_CHECK_SUBMODULE_REBASE      1736
#define IDC_TOTAL_LINE_WITHOUT_NEW_DEL  1737
#define IDC_TOTAL_LINE_WITHOUT_NEW_DEL_VALUE 1738
#define IDC_TOTAL_LINE_WITH_NEW_DEL     1739
#define IDC_TOTAL_LINE_WITH_NEW_DEL_VALUE 1740
#define IDC_CALC_DIFF                   1741
#define IDC_CHECK_MERGE_LOG             1742
#define IDC_EDIT_MERGE_LOGNUM           1743
#define IDC_ENABLELOGCACHE              1744
#define IDC_COMBO_MERGESTRATEGY         1745
#define IDC_COMBO_STRATEGYOPTION        1746
#define IDC_EDIT_STRATEGYPARAM          1747
#define IDC_LIST_PATH                   1748
#define IDC_PROG_LABEL                  1749
#define IDC_STATIC_ORDER                1750
#define IDC_COMBOBOXEX_ORDERING         1751
#define IDC_COMBO_SIMPLECREDENTIAL      1752
#define IDC_BUTTON_RENAME_REMOTE        1753
#define IDC_CHECK_SUBMODULE_REMOTE      1754
#define IDC_SMTPDELIVERYCOMBO           1754
#define IDC_EDITTGITCONFIG              1755
#define IDC_SMTPENCRYPTIONCOMBO         1756
#define IDC_STATIC_SMTPSERVER           1757
#define IDC_STATIC_SMTPPORT             1758
#define IDC_COMBO_CONFIGTYPE            1759
#define IDC_STATIC_SMTPENCRYPTION       1759
#define IDC_COMBO_HELPER                1760
#define IDC_STATIC_SMTPLOGIN            1760
#define IDC_CHECK_USEHTTPPATH           1761
#define IDC_STATIC_SMTPPASSWORD         1761
#define IDC_REVGRAPHUSELOCALFORCUR      1762
#define IDC_LOGGRAPHLINEWIDTH           1763
#define IDC_LOGGRAPHNODESIZE            1764
#define IDC_PIC_AUTHOR                  1765
#define IDC_ENABLEGRAVATAR              1766
#define IDC_GRAVATARURL                 1767
#define IDC_CONFIRMKILLPROCESS          1768
#define IDC_SYNCDIALOGRANDOMPOS         1769
#define IDC_RADIO_SETTINGS_EFFECTIVE    1770
#define IDC_RADIO_SETTINGS_LOCAL        1771
#define IDC_RADIO_SETTINGS_PROJECT      1772
#define IDC_RADIO_SETTINGS_GLOBAL       1773
#define IDC_RADIO_SETTINGS_SYSTEM       1774
#define IDC_COMBO_SETTINGS_SAFETO       1775
#define IDC_WALKBEHAVIOUR               1776
#define IDC_VIEW                        1777
#define IDC_ICONFILE_BROWSE             1778
#define IDC_ICONFILE                    1779
#define IDC_CHECK_INHERIT_NAME          1780
#define IDC_CHECK_INHERIT_LIMIT         1780
#define IDC_CHECK_INHERIT_BTREGEXP      1780
#define IDC_CHECK_INHERIT_EMAIL         1781
#define IDC_CHECK_INHERIT_BORDER        1781
#define IDC_CHECK_INHERIT_BTURL         1781
#define IDC_REFCOMPAREHIDEUNCHANGED     1781
#define IDC_CHECK_INHERIT_KEYID         1782
#define IDC_CHECK_INHERIT_ICONPATH      1782
#define IDC_CHECK_INHERIT_BTMSG         1782
#define IDC_PROGRESSDLG_SHOW_TIMES      1782
#define IDC_CHECK_INHERIT_BTLABEL       1783
#define IDC_CURRENTBRANCH               1784
#define IDC_CHECK_PRUNEALL              1785
#define IDC_CHECK_PUSHDEFAULT           1786
#define IDC_TESTBUGTRAQREGEXBUTTON      1787
#define IDC_ENABLEDRAGCONTEXTMENU       1788
#define IDC_DIFFOPTION                  1789
#define IDC_BUTTON_REVERSE              1790
#define IDC_CHECK_INHERIT_BTUUID32      1791
#define IDC_CHECK_INHERIT_BTUUID64      1792
#define IDC_CHECK_INHERIT_BTPARAMS      1793
#define IDC_EDIT_PUSHURL                1794
#define IDC_SORTTAGSREVERSED            1795
#define IDC_STATIC_FORCE                1796
#define IDC_OPENCERT                    1797
#define IDC_ERRORDESC                   1798
#define IDC_ERROR                       1799
#define IDC_SHA1                        1800
#define IDC_SHA256                      1801
#define IDC_ISSUER                      1802
#define IDC_COMMONNAME                  1803
#define IDC_SHOWDESCRIBE                1804
#define IDC_DESCRIBEALWAYSLONG          1805
#define IDC_DESCRIBESTRATEGY            1806
#define IDC_DESCRIBEABBREVIATEDSIZE     1807
#define IDC_FORECOMMANDCOLOR            1808
#define IDC_BACKCOMMANDCOLOR            1809
#define IDC_FOREPOSITIONCOLOR           1810
#define IDC_BACKPOSITIONCOLOR           1811
#define IDC_FOREHEADERCOLOR             1812
#define IDC_BACKHEADERCOLOR             1813
#define IDC_FORECOMMENTCOLOR            1814
#define IDC_BACKCOMMENTCOLOR            1815
#define IDC_FOREADDEDCOLOR              1816
#define IDC_BACKADDEDCOLOR              1817
#define IDC_FOREREMOVEDCOLOR            1818
#define IDC_BACKREMOVEDCOLOR            1819
#define IDC_BASEHASH                    1820
#define IDC_BASESUBJECT                 1821
#define IDC_MINECHANGETYPE              1822
#define IDC_MINEHASH                    1823
#define IDC_MINESUBJECT                 1824
#define IDC_BUTTON_UPDATE2              1825
#define IDC_BUTTON_UPDATE3              1826
#define IDC_REBASE_SPLIT_COMMIT         1827
#define IDC_SUBMIT_TO_CP_LABEL          1832
#define IDC_CREATE_CP_BUTTON            1833
#define IDC_SUBMIT_CP_BUTTON            1834
#define IDC_STATIC_PRUNE                1909
#define IDC_RADIO_SVN_COMMIT            2152
#define IDC_RADIO_GIT_COMMIT            2153
#define IDC_NOCONTEXTPATHS              2752
#define IDC_LOG_ALLBRANCH               3936
#define IDC_REBASE_COMBOXEX_UPSTREAM    4564
#define IDC_REBASE_COMBOXEX_BRANCH      4565
#define IDC_REBASE_STATIC_BRANCH        4566
#define IDC_REBASE_STATIC_UPSTREAM      4567
#define IDD_RESOLVE_CONFLICT            4568
#define IDC_MODIFY                      4569
#define IDD_SETTINGIT_CONFIG            4569
#define IDC_DEL_GROUP                   4570
#define IDD_SETTINREMOTE                4570
#define IDC_DELETE                      4571
#define IDD_SETTINGSBUGTRAQ_CONFIG      4571
#define IDC_LOCAL_STATUS                4572
#define IDD_CLEAN                       4572
#define IDC_REMOTE_STATUS               4573
#define IDD_SETTINGSEXTMENU             4573
#define IDD_BISECTSTART                 4574
#define IDD_STASH                       4575
#define IDD_DIFFSUBMODULE               4576
#define IDD_IGNORE                      4577
#define IDD_SUBMODULE_UPDATE            4578
#define IDD_DELETEREMOTETAG             4579
#define IDD_REVISIONGRAPH               4580
#define IDR_REVGRAPHBAR                 4581
#define IDR_REVGRAPHGLYPHS              4582
#define ID_REVGRAPH_ZOOMCOMBO           4583
#define IDD_REVGRAPHFILTER              4584
#define IDC_FROMREV                     4585
#define IDD_USER_PASSWD                 4585
#define IDC_TOREV                       4587
#define IDD_SETTINGSCREDENTIAL          4591
#define IDD_MERGEABORT                  4592
#define IDD_SETTINGSDIALOGS3            4593
#define IDD_CERTCHECK                   4594
#define IDD_RESOLVESUBMODULECONFLICT    4595
#define IDD_SICOMMITDLG                 4596
#define IDC_COMBOBOXEX_LOCAL_BRANCH     5000
#define IDC_COMBOBOXEX_REMOTE_BRANCH    5001
#define IDC_COMBOBOXEX_BAD              5001
#define IDC_LABEL2                      5002
#define IDC_USER_NAME                   9692
#define IDC_USER_PASSWORD               9693
#define ID_VIEW_ZOOMIN                  32772
#define ID_VIEW_ZOOMOUT                 32773
#define ID_VIEW_ZOOM100                 32803
#define ID_VIEW_ZOOMALL                 32804
#define ID_FILE_SAVESTATGRAPHAS         32806
#define ID_VIEW_ZOOMHEIGHT              32809
#define ID_VIEW_ZOOMWIDTH               32810
#define ID_VIEW_SHOWOVERVIEW            32813
#define IDC_SUBMIT_CP_COMBOBOX          32814
#define ID_LOGDLG_REFRESH               32821
#define ID_LOGDLG_FIND                  32822
#define ID_LOGDLG_FOCUSFILTER           32825
#define ID_FOCUS_MESSAGE                32837
#define ID_VIEW_FILTER                  32839
#define ID_FILE_SAVEGRAPHAS             32841
#define ID_MENUEXIT                     32842
#define ID_MENUHELP                     32843
#define ID_VIEW_COMPAREREVISIONS        32844
#define ID_VIEW_COMPAREHEADREVISIONS    32845
#define ID_VIEW_UNIFIEDDIFF             32846
#define ID_VIEW_UNIFIEDDIFFOFHEADREVISIONS 32847
#define IDI_REVGRAPHBAR                 32850
#define ID_FOCUS_FILELIST               32857
#define IDC_DETECT_MOVED_OR_COPIED_LINES 32858
#define IDC_SHOWCOMPLETELOG             32864
#define IDC_DETECT_MOVED_OR_COPIED_LINES_NUM_CHARACTERS_WITHIN_FILE 32865
#define IDC_DETECT_MOVED_OR_COPIED_LINES_NUM_CHARACTERS_FROM_FILES 32866
#define ID_GO_FORWARD                   32867
#define ID_GO_BACKWARD                  32868
#define ID_GO_UP                        32869
#define ID_GO_DOWN                      32870
#define ID_GO_BACKWARD_SELECT           32871
#define ID_GO_FORWARD_SELECT            32872
#define ID_SELECT_SEARCHFIELD           32873
#define IDR_ACC_SICOMMITDLG             32876

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        370
#define _APS_NEXT_COMMAND_VALUE         32878
#define _APS_NEXT_CONTROL_VALUE         1835
#define _APS_NEXT_SYMED_VALUE           201
#endif
#endif
